### PR TITLE
Do not run mdns scanning on require()

### PR DESCRIPTION
**Pull request by shinuza**
**Disclaimer:** This is incomplete.

Scanning at require() causes a lot of problems in my case. This is what we should do:

- [ ] Do not scan at require()
- [ ] Add a way to feed the receiverList other than the default method
- [ ] Update documentation

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
This is inconsistent with the `chrome.cast` implementation and will be a breaking change.  Can you explain a bit more in detail why you feel it is required to deviate from the spec?

**Comment by shinuza** [comment]
I would at least be able to change the method used to fetch the cast capable devices on the network. `node-mdns-easy` just doesn't work for me at all, while `node_mdns`, `bonjour` and `node-mdns-js` work properly, although only `node_mdns` does multi-interface browsing.

**Comment by MarshallOfSound** [comment]
@shinuza That doesn't make much sense as behind the scenes `node-mdns-easy` is literally a wrapper around `node-mdns-js` and `node_mdns`.   Don't forget you can only have one implementation of Bonjour running at a time on any system (as per the spec), so when you are testing these out if you leave some running it can break others.

`node-mdns-easy` is working nicely for thousands of people 👍 so whatever is going wrong is probably specific to your bonjour instances on your machine.  Restarting the Bonjour service (if you are on windows) can sometimes help.

If you can come up with a way to make this compliant with the current `chrome.cast` spec (I.e. no extra methods on existing classes) I would consider it, but my main goal with this library is not to bring Chromecast support to Electron, rather to **exactly** mirror the `chrome.cast` API.  This is because the main usage of this library is to drop into websites expecting the Chromecast API and they will "Just Work"(tm)

**Comment by shinuza** [comment]
I get your point 100%. I'm going to push my investigation futhermore as the following snippet works perfectly:

``` js
const Mdns = require('node-mdns-easy').default;

const mdns = new Mdns();
const browser = mdns.createBrowser(mdns.getLibrary().tcp('googlecast'));

browser.on('serviceUp', (service) => {
  console.log(service)
});

if (browser.ready) {
  browser.browse();
} else {
  browser.once('ready', () => {
    browser.browse();
  });
}
```

I'm thinking I may have a MODULE_VERSION conflict inside electron.
Thank you for taking the time to reply.

**Comment by MarshallOfSound** [comment]
Yeah, you need to use `electron-rebuild` with all native dependencies when using Electron

**Pull request closed without merging**
